### Numpy Concept

In [1]:
!pip install numpy

In [2]:
import numpy as np 


In [3]:
arr=np.array([5,6,7,8])

In [4]:
print(arr)

[5 6 7 8]


In [5]:
arr

array([5, 6, 7, 8])

In [6]:
print(arr)

[5 6 7 8]


### basic array creation 

In [7]:
import numpy as np

In [8]:
arr=np.array([2,3,4,5])

In [9]:
arr


array([2, 3, 4, 5])

In [10]:
arr=np.array([ [2,4],[4,5],[6,7]])
arr

array([[2, 4],
       [4, 5],
       [6, 7]])

In [11]:
arr= np.array([[[2,3],[4,5],[6,7],[7,8]]])
arr

array([[[2, 3],
        [4, 5],
        [6, 7],
        [7, 8]]])

In [12]:
a=np.array([[1,3],[7,8]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 2)
4
int64


In [13]:
arr=np.array([2,3,"hello"])
arr

array(['2', '3', 'hello'], dtype='<U21')

### Array genaration function

In [14]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [15]:
print(arr)

[1 2 3 4 5]


In [16]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [17]:
arr= np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr=np.ones([6,7],dtype=int)
arr

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [20]:
arr=np.linspace(2,10,5)
arr

array([ 2.,  4.,  6.,  8., 10.])

#### Random generation

In [23]:
arr=np.random.randint(5)
arr

1

In [27]:
arr = np.random.randint(10,20,6)
arr

array([18, 12, 13, 18, 19, 17], dtype=int32)

## Normalization  generate no between 0 and 1

In [29]:
arr=np.random.rand(4)
arr

array([0.61776654, 0.22598739, 0.58043702, 0.99330107])

#####  Standardation generate no between -3 to 3 

In [28]:
arr = np.random.randn(6)
arr

array([ 0.64696103, -1.23917749, -0.88410281, -0.48237722, -1.29638271,
       -0.58147109])

##### Array Attributes means methods

In [36]:
arr = np.array([[2,3],[4,5],[6,7]])
arr

array([[2, 3],
       [4, 5],
       [6, 7]])

In [37]:
arr.size

6

In [38]:
arr.shape

(3, 2)

In [35]:
arr.dtype

dtype('int64')

### Array Methods

In [40]:
arr=np.array([[2,3],[4,5],[7,8],[9,3]])
arr

array([[2, 3],
       [4, 5],
       [7, 8],
       [9, 3]])

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.min()

np.int64(2)

In [43]:
arr.sum()

np.int64(41)

In [44]:
arr.min()

np.int64(2)

In [47]:
arr.std()

np.float64(2.4206145913796355)

In [49]:
np.sum(arr,axis=1)

array([ 5,  9, 15, 12])

In [50]:
arr.sum(axis=0)

array([22, 19])

In [54]:
arr.argmax()

np.int64(6)

In [55]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr.reshape(5,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

### thanks