In [2]:
import numpy as np

### Matrix Operation

In [15]:
arr1 = np.array([[2,3],[4,5]])
arr2= np.array([[7,8],[9,3]])
print(arr1)
print(arr2)

[[2 3]
 [4 5]]
[[7 8]
 [9 3]]


In [16]:
arr1@arr2

array([[41, 25],
       [73, 47]])

In [17]:
n=np.dot(arr1,arr2)
n

array([[41, 25],
       [73, 47]])

#### ques 1 genarate 10 no between 1 and 100

In [28]:
arr= np.random.randint(1,101,10)
print(arr)
arr.mean()

[ 4 72 40 47 31 39 11 20 35 89]


np.float64(38.8)

In [29]:
np.mean(arr)

np.float64(38.8)

### calculate the median of no ..array [10,5,8,12,3,7]

arr= np.array([10,5,8,12,3,7])
c=np.sort(arr)
print(c)
np.median(arr)

### Genearte no and find standard deviation

In [27]:
arr=np.random.randint(1,51,15)
print(arr)
np.std(arr)

[50 19 20 35 14  7  5 18 49 24 10 37 28 28  9]


np.float64(13.826865958062305)

#### Create a 3*3 matrix and find row wise mean

In [36]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
c=np.mean(arr1,axis=1)
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

#### for an array [4,6,8,10,12]. calculate mean ,median ,std

In [37]:
arr=np.array([4,6,8,10,12])
c=np.mean(arr)
print(c)
print(np.std(arr))
print(np.sort(arr))
print(np.median(arr))

8.0
2.8284271247461903
[ 4  6  8 10 12]
8.0


### or better way 

In [40]:
data=np.array([4,6,8,10,12])
mean_data=np.mean(data)
medain_data=np.median(data)
std_data=np.std(data)
print(mean_data)
print(medain_data)
print(std_data)

8.0
8.0
2.8284271247461903


### generate a 5*5 numpy array of random int (1 to 100)

In [50]:
arr=np.random.randint(0,101,(5,5))
arr

array([[91, 50, 75, 60, 95],
       [91, 49, 45, 35, 44],
       [66, 43, 83, 20, 59],
       [90, 24, 42, 92, 80],
       [38, 10, 83, 78, 71]], dtype=int32)

In [51]:
arr=np.random.randint(0,101,50)
np.std(arr)

np.float64(31.226501565176978)

### find the indices od non-zero elements from[1,2,0,0,4,0]

In [52]:
arr_zero=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr_zero)
indices

(array([0, 1, 4]),)

## Thanks 